# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - full_body_controller

  full_body_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - planar_x
      - planar_y
      - planar_theta
      - left_fr3v2_joint1
      - left_fr3v2_joint2
      - left_fr3v2_joint3
      - left_fr3v2_joint4
      - left_fr3v2_joint5
      - left_fr3v2_joint6
      - left_fr3v2_joint7
      - right_fr3v2_joint1
      - right_fr3v2_joint2
      - right_fr3v2_joint3
      - right_fr3v2_joint4
      - right_fr3v2_joint5
      - right_fr3v2_joint6
      - right_fr3v2_joint7